SPDX-License-Identifier: CC-BY-SA-4.0 OR BSD-2-Clause
bsp: BSP
config: Config
copyrights:
- Copyright (C) 2026 embedded brains GmbH & Co. KG
component-type: generic
enabled-by: true
enabled-set: []
links:
- hash: null
  name: component
  role: input
  uid: ../../component
pkg-type: component
type: pkg
