SPDX-License-Identifier: CC-BY-SA-4.0 OR BSD-2-Clause
copyrights:
- Copyright (C) 2021 embedded brains GmbH & Co. KG
copyrights-by-license: {}
directory: ${.:/component/deployment-directory}
directory-state-type: explicit
enabled-by: true
files: []
hash: null
links:
- hash: null
  name: component
  role: input
  uid: ../component
- hash: null
  name: verify-package
  role: input-to
  uid: doc-package-manual
pkg-type: directory-state
type: pkg
