SPDX-License-Identifier: CC-BY-SA-4.0 OR BSD-2-Clause
actions:
- action: mkdir
  enabled-by: true
  exist-ok: true
  parents: true
  path: ${.:/directory}/spec/target/arch/soc/user
- action: touch
  enabled-by: true
  exist-ok: true
  path: ${.:/directory}/spec/target/arch/soc/user.yml
- action: touch
  enabled-by: true
  exist-ok: true
  path: ${.:/directory}/spec/target/arch/soc/user/perf-default.yml
- action: touch
  enabled-by: true
  exist-ok: true
  path: ${.:/directory}/spec/target/arch/soc/user/perf-smp.yml
- action: touch
  enabled-by: true
  exist-ok: true
  path: ${.:/directory}/spec/target/arch/soc/user/test-timeouts.yml
- action: mkdir
  enabled-by: true
  exist-ok: true
  parents: true
  path: ${.:/directory}/spec/pkg/arch/bsp/config
- action: touch
  enabled-by: true
  exist-ok: true
  path: ${.:/directory}/spec/pkg/arch/bsp/config/doc-user-tr.yml
copyrights:
- Copyright (C) 2026 embedded brains GmbH & Co. KG
copyrights-by-license: {}
directory: ${.:/component/deployment-directory}
directory-state-type: explicit
enabled-by: true
files:
- file: spec/target/arch/soc/user.yml
  hash: null
- file: spec/target/arch/soc/user/perf-default.yml
  hash: null
- file: spec/target/arch/soc/user/perf-smp.yml
  hash: null
- file: spec/target/arch/soc/user/test-timeouts.yml
  hash: null
- file: spec/pkg/arch/bsp/config/doc-user-tr.yml
  hash: null
hash: null
links:
- hash: null
  name: component
  role: input
  uid: ../component
pkg-type: directory-state
type: pkg
